{
 "title": "Fluentd",
 "description": "fluentd 1.x deployed in kubernetes and scraped by prometheus",
 "tags": [
  "fluentd",
  "logging"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluentd output error/retry rate",
   "type": "graph",
   "description": "If you see errors then you probably have serious issues with log processing, see https://docs.fluentd.org/buffer#handling-unrecoverable-errors\n\nRetries are normal but should occur only from time to time, otherwise check for network errors or destination is too slow and requires additional tuning per given provider.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(fluentd_output_status_retry_count[5m])) by (instance, type))",
     "legendFormat": "Retry rate: {{ instance }}-{{ type }}"
    },
    {
     "expr": "topk(5, sum(rate(fluentd_output_status_num_errors[5m])) by (instance, type))",
     "legendFormat": "Error rate: {{ instance }}-{{ type }}"
    }
   ]
  },
  {
   "title": "Input /  output rate",
   "type": "graph",
   "description": "Input  and output total rates",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(fluentd_output_status_write_count[5m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "fluentd output status buffer available space ratio",
   "type": "graph",
   "description": "This should not reach 0 otherwise logs are blocked from processing or even dropped",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(fluentd_output_status_buffer_available_space_ratio)",
     "legendFormat": "lowest across all hosts"
    }
   ]
  },
  {
   "title": "fluentd output status flush time count rate",
   "type": "graph",
   "description": "total flush time",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_flush_time_count[5m])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(fluentd_output_status_slow_flush_count[5m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Current total size of stage and queue buffers.",
   "type": "graph",
   "description": "Current total size of stage and queue buffers.\nfluentd_output_status_buffer_total_bytes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_total_bytes) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input entries rate (total)",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[5m])) ",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Input entries rate per hostname",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[5m])) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Input entries rate per namespace",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[5m])) by (kubernetes_namespace)",
       "legendFormat": "{{ kubernetes_namespace }}"
      }
     ]
    },
    {
     "title": "Input entries rate per instance",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[5m])) by (instance)",
       "legendFormat": "{{ kubernetes_namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input details - By Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input entries rate per tag",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(rate(fluentd_input_status_num_records_total[5m])) by (tag))",
       "legendFormat": "{{tag}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current length of stage buffers.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_stage_length",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_length) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current total size of stage buffers.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_stage_byte_size",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_byte_size) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum buffer length in last 5min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length[5m])",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    },
    {
     "title": "Maximum buffer bytes in last 1min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_total_bytes[5m])",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current length of queue buffers.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_queue_length",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current total size of queue buffers.",
     "type": "graph",
     "description": "fluentd_output_status_queue_byte_size",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_queue_byte_size) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ratio of available space in buffer.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_available_space_ratio",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_available_space_ratio) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Retries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current retry counts.",
     "type": "graph",
     "description": "fluentd_output_status_retry_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current emit records",
     "type": "graph",
     "description": "fluentd_output_status_emit_records",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current emit counts rate",
     "type": "graph",
     "description": "fluentd_output_status_emit_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current rollback counts",
     "type": "graph",
     "description": "fluentd_output_status_rollback_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_rollback_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current write counts",
     "type": "graph",
     "description": "fluentd_output_status_write_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_write_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current slow flush counts",
     "type": "graph",
     "description": "fluentd_output_status_slow_flush_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_slow_flush_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current retry wait",
     "type": "graph",
     "description": "fluentd_output_status_retry_wait",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_wait[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total flush time",
     "type": "graph",
     "description": "fluentd_output_status_flush_time_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_flush_time_count[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current number of errors rate",
     "type": "graph",
     "description": "fluentd_output_status_num_errors",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer timekeys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timekey diff",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fluentd_output_status_buffer_newest_timekey - fluentd_output_status_buffer_oldest_timekey",
       "legendFormat": "{{kubernetes_pod_name}} {{ type}}"
      }
     ]
    },
    {
     "title": "Newest timekey in buffer.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_newest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_newest_timekey) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    },
    {
     "title": "Oldest timekey in buffer.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_oldest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_oldest_timekey) by (kubernetes_pod_name, type)",
       "legendFormat": "{{kubernetes_pod_name}} {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}